# Generated by Django 5.2 on 2025-08-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
